version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./myproject/:/app/myproject

volumes:
  db_data:
